name: Terraform Apply

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: "1949ddb6-15d6-44b2-b00e-970a055709d8"
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: "88e98c7d-911a-45db-87e2-c788bd626c53"
      ARM_TENANT_ID: "04645680-c487-4ccf-8a42-6d4b6a5dfa97"

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: open Az storage fw
        run: |
          export mypublicip="$(dig +short myip.opendns.com @resolver1.opendns.com)"
          az storage account network-rule add --resource-group "tstate" --account-name "tstate25079" --ip-address $mypublicip

      - name: Terraform Init
        run: terraform init -backend-config="access_key=$(az storage account keys list --resource-group "tstate" --account-name "tstate25079" --query '[0].value' -o tsv)"

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: close Az storage fw
        run:  az storage account network-rule remove --resource-group "tstate" --account-name "tstate25079" --ip-address $mypublicip
